### ISSUE TITLE
Can't get it to work, I'm afraid

### ISSUE THREAD

**Issue by christianaj** [danabr/SupportNotifications#1]
I really like the idea of this plug in but it won't authenticate with my zendesk account.

Could it be because I'm mapping the zendesk domain to my own domain?

After I put in all the details, it tells me it can't authenticate.  When I click on the Zendesk? link, it takes me to a 404 URL:
http://megatron1.zendesk.com/rules/871014

Any suggestions?

Regards
cm

**Comment by danabr** [comment]
Is megatron1 your company id at zendesk? If so, could you please log into your account, and report the URL to the page which says"My unsolved tickets", and lists all your tickets. It might happen that the rule does not apply to your account, and we have to use something else.

We also use a custom domain name, but we also have a "ourcompany.zendesk.com" domain. It is the "ourcompany" part that you need to specify in the "Company id" field.

**Comment by christianaj** [comment]
Yes, my zendesk id is megatron1.  My zendesk url is helpdesk.megatron1.com.  Although http://megatron1.zendesk.com also works.

Either way, I just have megatron1 in the settings.

My 'my working tickets' URL is http://helpdesk.megatron1.com/rules/221311
My 'all working tickets' URL is http://helpdesk.megatron1.com/rules/221315

Hope this helps.

Regards
cm

**Comment by danabr** [comment]
Ok, so what does http://helpdesk.megatron1.com/rules/871014 give you? A 404?

**Comment by christianaj** [comment]
Yup.
c

**Comment by danabr** [comment]
Actually, I was afraid this would happen. I will have to have a second look into the API and see if it is somehow possible to find out which rules apply to a specific account.

Could you see what happens if you follow this link: http://helpdesk.megatron1.com/rules
In my case, I am redirected to "My unsolved tickets". If that is the case for everyone, then I might use that as a hack to get the correct rule to use.

**Comment by christianaj** [comment]
It bounces me to 'my working tickets'.

That sounds like it might work.

Best
c

**Comment by danabr** [comment]
Ok. Could you send the output from http://helpdesk.megatron1.com/views.xml to hamsson at gmail dot com?

I'll see if I can solve this after work.

**Comment by christianaj** [comment]
Done.

Best,
c

**Comment by danabr** [comment]
This should be fixed in version 1.0.1. Please test it and report any issues.

**Comment by christianaj** [comment]
Hi, thanks for the update.

I can now log in and it's successfully authenticated.  I've tested a few tickets, though - and it doesn't seem to be alerting me or doing anything.

It's got a green number 30 in it, which then takes me to the first page of 'my working tickets' when I click on the zendesk link.

Nothing happens if I click on 'check for new tickets'.

Am I missing something?

It would be helpful if I could choose which page view it was connecting to as I make my own views and usually work from a 'tickets over the last 48 hours' view.

Still, I'm sure there is more to come with this extension so I'll wait to see where things go.

Thanks
c

**Comment by danabr** [comment]
Hi Christian.

SupportNotifications currently just alerts about new tickets. The first time you start it, it sets the "latestTicketDate" to 00:00 AM the very same day. However, if you create a new ticket, it should certainly alert you. I have considered adding an option to also get alerted when tickets are updated.

I think I will have to separate what page to open when clicking the "Zendesk" link, and what page to use when checking for new tickets. I guess it should always check for new tickets from the "All unsolved tickets" view (871018). Could you check if that rule applies to your account as well? It seems sensible that view should exist for every account. It would be too bad if you had to specify the rule number to use  just to get started.

At last, if you want to know what the extension currently considers being new tickets. You can take the following steps:
- Open the extension management page ("Wrench"->"Tools"->"Extensions").
- Click on "bg.html"
- Open the development console (to the far right).
- Write localStorage["Zendesk.lastTicketCreated"] and hit enter
- You can update this value to some date a few days back, and then click "Check for new tickets" to see that it is actually working.

Thanks for the heads up. If no one would tell me about probems or ask for new features, no further development would have occurred, since it's working just fine for me. So keep notifying me about any problems.
