### ISSUE TITLE
Feature Request: desk.com and / or freshdesk support

### ISSUE THREAD

**Issue by ntemple** [danabr/SupportNotifications#5]
We're looking at moving to desk.com or freshdesk for various reasons. What would it take to add support for either (or both) of the aforementioned support desks?

Also, it would be great to be able to have multiple "instances" installed, especially during the transition, where we'll have some tickets in one or more systems.

**Comment by danabr-apoex** [comment]
Hi,

I'll have to investigate to find out. I have not used desk.com or freshdesk before, and not zendesk either for a long time. The code base is quite simple, so perhaps you have the possibility to add support for them yourself?

When it comes to having multiple instances, SupportNotifications can already handle multiple different "notification providers" at the same time. E.g. we have had support for getsatisfaction for quite some time and you can get notifications from both getsatisfaction and zendesk with the same instance.

**Comment by danabr** [comment]
Hi,

I just wanted to say that I've released a new version of SupportNotifications which adds Freshdesk support.

I do not know if this is still relevant to you, but I haven't had the time and energy to add support for it until now. I will look into adding support for desk.com as well, but it is a bit trickier since it uses oAuth.

**Comment by danabr** [comment]
Hi. This project has now been officially abandoned.
