### ISSUE TITLE
Must re-enter password on every restart.

### ISSUE THREAD

**Issue by astedfast** [danabr/SupportNotifications#7]
Each time I turn on my computer in the morning, I need to enter my master password.  Otherwise, there is always a "7" displayed, and no notifications show.  

Also, I feel that I clicked on a notification in the recent update, and it didn't open a window/tab.  Unfortunately, even in the last version, when I clicked on a notification with my Freshdesk window already open, a new tab would be opened.  I'd love for SupportNotifications to start automatically at boot (Chrome background process is fine), and open in a current opened Freshdesk window/tab or open one if there isn't one open when I click on the notification.

Thank you so much for this great extension--it gets noticeably better, each time!

**Comment by danabr** [comment]
Hi,

When it comes to the master password, the behavior you describe is exactly how it is meant to behave. The reason there is a master password is to encrypt and decrypt your credentials when storing and loading the extension configuration. If we do not do this, then your credentials would be stored in plain text on the disk. Since the configuration is read every time the browser is restarted, you will have to enter the master password each time. The only way to get away from this is to loosen security, something I'm not willing to do.

The other request is more reasonable though. It can probably be done via the chrome tab api (http://developer.chrome.com/extensions/tabs.html), where we would have to scan the tab list to find an existing tab. I'll consider this the next time I decided to work on this extension.

As always, feel free to download the source and implement this yourself. I am willing to merge any well-formed pull request.

**Comment by danabr** [comment]
Hi. This extension has been officially abandoned.
